In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(np.version)

[1 2 3 4 5]
<module 'numpy.version' from 'C:\\Users\\User\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
ar = np.array((1,2,3,4,5,6,7))
print(ar)

[1 2 3 4 5 6 7]


In [16]:
arr = np.array([[1,2,5],[4,6,7],[4,3,5],[2,1,3]])
print(arr)

[[1 2 5]
 [4 6 7]
 [4 3 5]
 [2 1 3]]


In [17]:
print(arr)
print(ar)


[[1 2 5]
 [4 6 7]
 [4 3 5]
 [2 1 3]]
[1 2 3 4 5 6 7]


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [19]:
arr = np.array([1, 2, 5, 4])
print(arr[2] + arr[3])


9


In [20]:
print(arr[-1])

4


In [25]:
arr.shape

(4,)